const SET_SNACKBAR = "SET_SNACKBAR";
const GET_USER_DATA = "GET_USER_DATA";
const LOGOUT = "LOGOUT";

const SET_TELEGRAM_CACHED_USERS = "SET_TELEGRAM_CACHED_USERS";
const SET_TELEGRAM_MESSAGE = "SET_TELEGRAM_MESSAGE";

export default {
  SET_SNACKBAR,
  GET_USER_DATA,
  LOGOUT,
  SET_TELEGRAM_CACHED_USERS,
  SET_TELEGRAM_MESSAGE,
};
