const SET_SNACKBAR = "SET_SNACKBAR";
const GET_USER_DATA = "GET_USER_DATA";
const LOGOUT = "LOGOUT";

const SET_TELEGRAM_CACHED_USERS = "SET_TELEGRAM_CACHED_USERS";
const SET_TELEGRAM_MESSAGE = "SET_TELEGRAM_MESSAGE";

const GET_JIRA_PROJECTS = "GET_JIRA_PROJECTS";
const SET_JIRA_PROJECTS = "SET_JIRA_PROJECTS";

const GET_TRELLO_BOARDS = "GET_TRELLO_BOARDS";
const SET_TRELLO_BOARDS = "SET_TRELLO_BOARDS";

const UPDATE_USER_SETTINGS = "UPDATE_USER_SETTINGS";

const CONFIRM_TWO_FA = "CONFIRM_TWO_FA";

const GET_STATISTIC = "GET_STATISTIC";

export default {
  SET_SNACKBAR,
  GET_USER_DATA,
  LOGOUT,
  SET_TELEGRAM_CACHED_USERS,
  SET_TELEGRAM_MESSAGE,
  GET_JIRA_PROJECTS,
  SET_JIRA_PROJECTS,
  GET_TRELLO_BOARDS,
  SET_TRELLO_BOARDS,
  UPDATE_USER_SETTINGS,
  CONFIRM_TWO_FA,
  GET_STATISTIC,
};
