const SET_LOADING = "SET_LOADING";
const SET_SNACKBAR = "SET_SNACKBAR";
const SET_USER_DATA = "SET_USER_DATA";

const SET_TELEGRAM_AUTH_LINK = "SET_TELEGRAM_AUTH_LINK";
const SET_TELEGRAM_AUTH_STATE = "SET_TELEGRAM_AUTH_STATE";

export default {
  SET_LOADING,
  SET_SNACKBAR,
  SET_USER_DATA,
  SET_TELEGRAM_AUTH_LINK,
  SET_TELEGRAM_AUTH_STATE,
};
