const SET_LOADING = "SET_LOADING";
const SET_SNACKBAR = "SET_SNACKBAR";
const SET_USER_DATA = "SET_USER_DATA";

const SET_TELEGRAM_AUTH_LINK = "SET_TELEGRAM_AUTH_LINK";
const SET_TELEGRAM_AUTH_STATE = "SET_TELEGRAM_AUTH_STATE";
const SET_TELEGRAM_CACHED_USERS = "SET_TELEGRAM_CACHED_USERS";
const SET_TELEGRAM_MESSAGE = "SET_TELEGRAM_MESSAGE";

const SET_FINGERPRINT = "SET_FINGERPRINT";

const SET_JIRA_PROJECTS = "SET_JIRA_PROJECTS";

const SET_TRELLO_BOARDS = "SET_TRELLO_BOARDS";

const SET_STATISTIC = "SET_STATISTIC";

export default {
  SET_LOADING,
  SET_SNACKBAR,
  SET_USER_DATA,
  SET_TELEGRAM_AUTH_LINK,
  SET_TELEGRAM_AUTH_STATE,
  SET_TELEGRAM_CACHED_USERS,
  SET_TELEGRAM_MESSAGE,
  SET_FINGERPRINT,
  SET_JIRA_PROJECTS,
  SET_TRELLO_BOARDS,
  SET_STATISTIC,
};
