export enum SocketEvents {
  CONNECT_MESSENGER = 'CONNECT_MESSENGER',
  MESSENGER_CONNECTED = 'MESSENGER_CONNECTED',
  REMOVE_MESSENGER = 'REMOVE_MESSENGER',
  MESSENGER_REMOVED = 'MESSENGER_REMOVED',
}